const KEY='molkky-score-v2';
const state=load()||{screen:'setup',savedNames:[],players:['',''],teams:false,order:'entry',sort:'turn',game:null,modal:null,profile:null,knownRecent:false,knownDelete:false};
function load(){try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){save();document.querySelector('#app').innerHTML=`<div class="app">${state.screen==='setup'?setupView():gameView()}${state.modal?modalView():''}${state.profile!==null?profileView():''}</div>`;bind()}
function setupView(){const known=[...state.savedNames].sort((a,b)=>state.knownRecent?(b.used||0)-(a.used||0):a.name.localeCompare(b.name,'fr'));return `<section class="hero"><small>NOUVELLE PARTIE</small><h1>Mölkky Score</h1></section><section class="card"><img class="placement-home" src="placement-quilles.png" alt="Placement initial des douze quilles"><h2>Qui joue ?</h2><div class="count-buttons">${Array.from({length:17},(_,i)=>i+2).map(n=>`<button data-count="${n}" class="${state.players.length===n?'active':''}">${n}</button>`).join('')}</div><div class="name-grid">${state.players.map((p,i)=>`<input data-player="${i}" value="${esc(p)}" placeholder="Joueur ${i+1}" aria-label="Nom du joueur ${i+1}">`).join('')}</div>${known.length?`<div class="known-head"><strong>Joueurs connus</strong><div class="mini-tools"><button id="knownSort">${state.knownRecent?'Récent':'A–Z'}</button><button id="knownDelete" class="${state.knownDelete?'active':''}">🗑</button></div></div><div class="known-list">${known.map(n=>`<button data-known="${esc(n.name)}" class="${state.players.includes(n.name)?'used':''}">${state.knownDelete?'× ':''}${esc(n.name)}</button>`).join('')}</div>`:''}<div class="segments">${[['entry','Saisie'],['alpha','A–Z'],['random','Aléatoire']].map(([v,l])=>`<button data-order="${v}" class="${state.order===v?'active':''}">${l}</button>`).join('')}</div><label class="row team-box"><input id="teams" type="checkbox" ${state.teams?'checked':''}><strong>Jouer en équipes</strong></label><div id="error"></div><button class="btn orange validate" id="start">COMMENCER LA PARTIE</button></section>`}
function gameView(){const g=state.game,p=g.players[g.current];return `<section class="hero"><small>MANCHE ${g.round} · JOUEUR ${g.current+1}/${g.players.length}${g.correction?' · MODIFICATION':''}</small><h1>À toi, ${esc(p.name)} !</h1></section><section class="card"><div class="score-head"><div><span class="muted">SCORE ACTUEL</span><div class="bigscore">${p.score}</div></div><div class="misses">${missIcons(p.misses)}</div></div></section><h3>Combien de points ?</h3><div class="score-grid">${Array.from({length:12},(_,i)=>`<button data-score="${i+1}" class="${g.pending===i+1?'selected':''}">${i+1}</button>`).join('')}</div><button class="btn orange validate" id="validate">${g.pending?`VALIDER ${g.pending} POINT${g.pending>1?'S':''}`:'VALIDER 0'}</button><div class="game-tools"><button class="btn ghost icon-only" id="undo" ${!g.actions.length||g.correction?'disabled':''} aria-label="Modifier le dernier lancer">↶</button>${g.correction?'<button class="btn ghost icon-only" id="resume" aria-label="Revenir">↷</button>':''}<span class="tool-spacer"></span><button class="btn ghost" id="quit">Terminer</button></div><div class="ranking-title"><h3 aria-label="Joueurs">♟</h3><select id="sort"><option value="turn" ${state.sort==='turn'?'selected':''}>Tour</option><option value="score" ${state.sort==='score'?'selected':''}>Score</option><option value="alpha" ${state.sort==='alpha'?'selected':''}>A–Z</option></select></div>${rankingRows(false)}`}
function missIcons(n){return `<span aria-label="${n} échec${n>1?'s':''}">${'×'.repeat(n)}${'○'.repeat(3-n)}</span>`}
function ordered(final=false){const a=state.game.players.map((p,i)=>({...p,i}));if(final||state.sort==='score')a.sort((x,y)=>y.score-x.score||x.i-y.i);else if(state.sort==='alpha')a.sort((x,y)=>x.name.localeCompare(y.name,'fr'));return a}
function trophy(rank){return rank<3?`<span class="trophy t${rank+1}">🏆</span>`:''}
function rankingRows(final){const list=ordered(final),showPodium=final||state.game.players.some(p=>p.finished);return list.map((p,rank)=>`<button class="player-row ${p.i===state.game.current&&!final?'current':''} ${p.eliminated?'eliminated':''} ${p.finished?'finished':''}" data-profile="${p.i}"><span class="turn-rank">${p.i+1}</span>${showPodium?trophy(rank):''}<strong class="row-name">${esc(p.name)}</strong><span class="row-misses">${missIcons(p.misses)}</span><strong>${p.score} pts</strong></button>`).join('')}
function stats(p){const vals=p.throws.map(t=>t.points),ok=vals.filter(v=>v>0);return{avg:ok.length?(ok.reduce((a,b)=>a+b,0)/ok.length).toFixed(1):'—',best:ok.length?Math.max(...ok):'—',fails:vals.filter(v=>v===0).length,overs:p.throws.filter(t=>t.overflow).length}}
function profileView(){const p=state.game.players[state.profile],s=stats(p);return `<div class="overlay profile-overlay"><section class="sheet"><header><div><small>FICHE DU JOUEUR</small><h2>${esc(p.name)}</h2></div><button class="icon-btn close-profile">×</button></header><div class="stat-grid"><div class="stat"><span>Score</span><b>${p.score}</b></div><div class="stat"><span>Moyenne</span><b>${s.avg}</b></div><div class="stat"><span>Meilleur lancer</span><b>${s.best}</b></div><div class="stat"><span>Échecs</span><b>${s.fails}</b></div><div class="stat"><span>Lancers</span><b>${p.throws.length}</b></div><div class="stat"><span>Retours à 25</span><b>${s.overs}</b></div></div><h3>Historique</h3>${p.throws.length?`<ol class="throws">${p.throws.map(t=>`<li><span>Manche ${t.round}</span><b>${t.points||'0'}</b><span>${t.after} pts</span></li>`).join('')}</ol>`:'<div class="empty">Aucun lancer.</div>'}</section></div>`}
function modalView(){const m=state.modal;if(m.type==='winner')return `<div class="overlay"><section class="sheet winner"><div class="trophy-big">🏆</div><h2>${esc(m.name)} gagne !</h2><button class="btn orange" id="continue">Continuer avec les autres</button><button class="btn ghost" id="finish">Voir le classement final</button></section></div>`;return `<div class="overlay"><section class="sheet final-sheet"><h2>Partie terminée</h2>${rankingRows(true)}<div class="final-actions"><button class="btn ghost" id="cancelFinal">Annuler</button><button class="btn orange" id="newgame">Nouvelle partie</button></div></section></div>`}
function bind(){document.querySelectorAll('[data-player]').forEach(x=>x.oninput=e=>{state.players[+e.target.dataset.player]=e.target.value;save()});document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{const n=+b.dataset.count;while(state.players.length<n)state.players.push('');state.players.length=n;render()});document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{state.order=b.dataset.order;render()});document.querySelector('#teams')?.addEventListener('change',e=>{state.teams=e.target.checked;render()});document.querySelector('#knownSort')?.addEventListener('click',()=>{state.knownRecent=!state.knownRecent;render()});document.querySelector('#knownDelete')?.addEventListener('click',()=>{state.knownDelete=!state.knownDelete;render()});document.querySelectorAll('[data-known]').forEach(b=>b.onclick=()=>knownClick(b.dataset.known));document.querySelector('#start')?.addEventListener('click',startGame);document.querySelectorAll('[data-score]').forEach(b=>b.onclick=()=>{state.game.pending=state.game.pending===+b.dataset.score?null:+b.dataset.score;render()});document.querySelector('#validate')?.addEventListener('click',commitThrow);document.querySelector('#undo')?.addEventListener('click',beginCorrection);document.querySelector('#resume')?.addEventListener('click',cancelCorrection);document.querySelector('#quit')?.addEventListener('click',()=>{state.modal={type:'final'};render()});document.querySelector('#sort')?.addEventListener('change',e=>{state.sort=e.target.value;render()});document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=e=>{e.stopPropagation();state.profile=+b.dataset.profile;render()});document.querySelector('.close-profile')?.addEventListener('click',closeProfile);document.querySelector('.profile-overlay')?.addEventListener('click',e=>{if(e.target===e.currentTarget)closeProfile()});document.querySelector('#continue')?.addEventListener('click',continueAfterWin);document.querySelector('#finish')?.addEventListener('click',()=>{state.game.players.find(p=>p.name===state.modal.name).finished=true;state.modal={type:'final'};render()});document.querySelector('#cancelFinal')?.addEventListener('click',()=>{state.modal=null;render()});document.querySelector('#newgame')?.addEventListener('click',()=>{state.screen='setup';state.game=null;state.modal=null;state.profile=null;render()})}
function closeProfile(){state.profile=null;render()}
function knownClick(name){if(state.knownDelete){if(confirm(`Supprimer ${name} de l’historique ?`))state.savedNames=state.savedNames.filter(n=>n.name!==name)}else{const at=state.players.indexOf(name);if(at>=0)state.players[at]='';else{const empty=state.players.findIndex(n=>!n.trim());if(empty>=0)state.players[empty]=name}}render()}
function startGame(){let names=state.players.map(x=>x.trim()).filter(Boolean),err=document.querySelector('#error');if(names.length<2){err.innerHTML='<div class="notice">Il faut au moins deux joueurs.</div>';return}if(new Set(names.map(n=>n.toLowerCase())).size!==names.length){err.innerHTML='<div class="notice">Deux noms sont identiques.</div>';return}if(state.teams){err.innerHTML='<div class="notice">La configuration détaillée des équipes reste à terminer.</div>';return}if(state.order==='alpha')names.sort((a,b)=>a.localeCompare(b,'fr'));if(state.order==='random')names.sort(()=>Math.random()-.5);const now=Date.now();names.forEach(name=>{const x=state.savedNames.find(n=>n.name.toLowerCase()===name.toLowerCase());x?x.used=now:state.savedNames.push({name,used:now})});state.game={players:names.map(name=>({name,score:0,misses:0,eliminated:false,finished:false,throws:[]})),current:0,round:1,pending:null,actions:[],correction:null};state.screen='game';render()}
function applyResult(p,points,round){let overflow=false;if(points===0){p.misses++;if(p.misses>=3)p.eliminated=true}else{p.misses=0;p.score+=points;if(p.score>50){p.score=25;overflow=true}}p.throws.push({round,points,after:p.score,overflow});return overflow}
function commitThrow(){const g=state.game,p=g.players[g.current],points=g.pending||0;if(g.correction){const a=g.actions[g.correction.index];p.score=a.before.score;p.misses=a.before.misses;p.eliminated=a.before.eliminated;p.finished=a.before.finished;p.throws.pop();applyResult(p,points,a.round);a.points=points;g.current=g.correction.resumeCurrent;g.round=g.correction.resumeRound;g.correction=null;g.pending=null;if(p.score===50)state.modal={type:'winner',name:p.name};render();return}const before={score:p.score,misses:p.misses,eliminated:p.eliminated,finished:p.finished};applyResult(p,points,g.round);g.actions.push({player:g.current,round:g.round,points,before});g.pending=null;if(p.score===50){state.modal={type:'winner',name:p.name};render();return}advance();render()}
function beginCorrection(){const g=state.game,a=g.actions.at(-1);if(!a)return;g.correction={index:g.actions.length-1,resumeCurrent:g.current,resumeRound:g.round};g.current=a.player;g.round=a.round;g.pending=a.points||null;render()}
function cancelCorrection(){const g=state.game,c=g.correction;if(!c)return;g.current=c.resumeCurrent;g.round=c.resumeRound;g.pending=null;g.correction=null;render()}
function continueAfterWin(){const p=state.game.players.find(p=>p.name===state.modal.name);p.finished=true;state.game.continueMode=true;state.modal=null;advance();render()}
function advance(){const g=state.game,active=g.players.filter(p=>!p.eliminated&&!p.finished).length;if(active===0||(!g.continueMode&&active<=1)){state.modal={type:'final'};return}let n=g.current;do{n=(n+1)%g.players.length;if(n===0)g.round++}while(g.players[n].eliminated||g.players[n].finished);g.current=n}
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
